import type {Direction,Look,Trait} from './style-types';
export const TRAITS:Record<Trait,string>={relaxed:'Relaxed shapes',fitted:'Close-fitting shapes',layers:'Layering',texture:'Tactile texture',neutral:'Quiet colors',color:'Expressive color',detail:'Little details',structure:'Tailored structure'};
export const DIRECTIONS:Record<Direction,{name:string;short:string;description:string;formula:string}>={
  soft:{name:'Soft romantic',short:'Softness',description:'Gentle volume, fluid lines, and details that feel collected rather than coordinated.',formula:'A soft blouse + a moving skirt + something grounded on your feet.'},
  minimal:{name:'Considered minimal',short:'Simplicity',description:'Space to breathe. Fewer elements, interesting proportions, and a quiet palette doing the work.',formula:'A simple top + generous trousers + a single small accessory.'},
  tailored:{name:'Playful tailoring',short:'Structure',description:'Crisp shapes without the formality. You can borrow from a suit without wearing a uniform.',formula:'One tailored layer + a softer base + a shoe you can walk in.'},
  expressive:{name:'Expressive eclectic',short:'Play',description:'Color, contrast, and combinations that keep an outfit from feeling too predictable.',formula:'One expressive piece + a contrasting color + an otherwise simple silhouette.'},
  utility:{name:'Everyday utility',short:'Ease',description:'Practical layers and easy movement, with enough shape and texture to feel intentional.',formula:'A useful outer layer + a roomy bottom + comfortable, substantial shoes.'},
  vintage:{name:'Collected vintage',short:'Nostalgia',description:'Warm tones, tactile fabrics, and a familiar shape with an unexpected little twist.',formula:'One nostalgic texture or print + clean proportions + a worn-in accessory.'},
};
const specs:Array<Omit<Look,'id'|'caption'|'background'>>=[
{name:'The slow morning',direction:'soft',top:'blouse',bottom:'skirt',shoes:'flats',pattern:'plain',accessory:'necklace',colors:['#eee5d1','#8c503f','#453930','#b3a27a'],traits:['relaxed','detail','neutral'],pieces:['Ivory tie-neck blouse','Terracotta flowing midi skirt','Brown ballet flats']},
{name:'Room to breathe',direction:'minimal',top:'tank',bottom:'wide',shoes:'flats',pattern:'plain',accessory:'bag',colors:['#484d41','#e2ddc8','#4b352c','#5c4634'],traits:['relaxed','neutral'],pieces:['Olive ribbed tank','Ecru wide-leg trousers','Brown flat sandals']},
{name:'Off the clock',direction:'tailored',top:'blazer',bottom:'straight',shoes:'loafers',pattern:'plain',accessory:'belt',colors:['#787665','#3f4841','#342e29','#4f3527'],traits:['structure','layers','neutral'],pieces:['Olive relaxed blazer','Charcoal straight-leg trousers','Brown penny loafers']},
{name:'A little unexpected',direction:'expressive',top:'knit',bottom:'pleated',shoes:'sneakers',pattern:'plain',accessory:'bag',colors:['#ae493b','#c0b9cf','#f0e6d4','#75927c'],traits:['color','texture','relaxed'],pieces:['Tomato red crewneck sweater','Lilac pleated midi skirt','Cream low-top sneakers']},
{name:'Out of office',direction:'utility',top:'jacket',bottom:'wide',shoes:'sneakers',pattern:'plain',accessory:'none',colors:['#727c61','#d1c4a3','#e3e0d2','#c5b58c'],traits:['layers','relaxed','texture'],pieces:['Olive chore jacket','Sand wide-leg cotton trousers','Off-white canvas sneakers']},
{name:'Sunday at the market',direction:'vintage',top:'vest',bottom:'flare',shoes:'boots',pattern:'plain',accessory:'scarf',colors:['#9e6844','#657580','#563b2c','#805945'],traits:['texture','layers','detail'],pieces:['Caramel knitted vest','Washed indigo flared jeans','Brown ankle boots']},
{name:'Pressed flowers',direction:'soft',top:'tank',bottom:'skirt',shoes:'flats',pattern:'floral',accessory:'necklace',colors:['#eee1cc','#8d967a','#ded3b9','#d4b475'],traits:['detail','fitted','color'],pieces:['Ivory scoop-neck top','Sage floral midi skirt','Cream Mary Jane flats']},
{name:'The quiet line',direction:'minimal',top:'knit',bottom:'straight',shoes:'loafers',pattern:'plain',accessory:'none',colors:['#d8d3c5','#e6e0d0','#4a3f34','#a69b7e'],traits:['neutral','texture','relaxed'],pieces:['Oatmeal fine-knit sweater','Ecru straight-leg trousers','Chocolate loafers']},
{name:'Borrowed from the boys',direction:'tailored',top:'shirt',bottom:'wide',shoes:'loafers',pattern:'stripe',accessory:'tie',colors:['#9aaebc','#555b56','#3b332c','#796246'],traits:['structure','detail','layers'],pieces:['Blue striped button-down','Charcoal pleated wide-leg trousers','Dark brown loafers']},
{name:'Color outside the lines',direction:'expressive',top:'shirt',bottom:'wide',shoes:'flats',pattern:'plain',accessory:'necklace',colors:['#b4bd66','#6975a1','#9a4037','#bea357'],traits:['color','relaxed','detail'],pieces:['Chartreuse cotton shirt','Periwinkle wide-leg trousers','Red ballet flats']},
{name:'The long way home',direction:'utility',top:'hoodie',bottom:'straight',shoes:'sneakers',pattern:'plain',accessory:'bag',colors:['#b5b8a4','#475347','#e0d9c6','#a27448'],traits:['relaxed','layers','neutral'],pieces:['Sage heavyweight hoodie','Olive straight-leg cotton pants','Natural canvas sneakers']},
{name:'Found in a bookshop',direction:'vintage',top:'knit',bottom:'pleated',shoes:'boots',pattern:'check',accessory:'bag',colors:['#76473b','#b2a086','#5d4431','#8a5a38'],traits:['texture','detail','neutral'],pieces:['Burgundy ribbed sweater','Brown checked pleated skirt','Dark brown ankle boots']},
{name:'A soft landing',direction:'soft',top:'blouse',bottom:'wide',shoes:'flats',pattern:'plain',accessory:'scarf',colors:['#d6b3a7','#e8e0cb','#836855','#ab7562'],traits:['relaxed','color','detail'],pieces:['Dusty rose gathered blouse','Cream flowing wide-leg pants','Taupe ballet flats']},
{name:'Nothing extra',direction:'minimal',top:'tee',bottom:'skirt',shoes:'flats',pattern:'plain',accessory:'belt',colors:['#ece9dd','#343b37','#3b352e','#7d674d'],traits:['neutral','fitted'],pieces:['White fitted cotton tee','Black column midi skirt','Black simple flats']},
{name:'The lighter suit',direction:'tailored',top:'vest',bottom:'wide',shoes:'loafers',pattern:'plain',accessory:'none',colors:['#c2bca9','#c9c3ad','#5e4b3a','#8e7a5e'],traits:['structure','layers','neutral'],pieces:['Oatmeal tailored waistcoat','Oatmeal pleated wide-leg trousers','Tan penny loafers']},
{name:'Quite a combination',direction:'expressive',top:'blouse',bottom:'skirt',shoes:'heels',pattern:'floral',accessory:'bag',colors:['#527664','#c89473','#985344','#bcc370'],traits:['color','detail','fitted'],pieces:['Green floral blouse','Peach A-line midi skirt','Terracotta low block heels']},
{name:'Somewhere outdoors',direction:'utility',top:'tee',bottom:'shorts',shoes:'boots',pattern:'plain',accessory:'bag',colors:['#d2cec0','#85836a','#4d4536','#a87a49'],traits:['relaxed','neutral'],pieces:['Natural cotton oversized tee','Olive tailored walking shorts','Brown lace-up boots']},
{name:'An old favorite',direction:'vintage',top:'shirt',bottom:'flare',shoes:'loafers',pattern:'stripe',accessory:'belt',colors:['#bc9570','#754f39','#42372a','#523b29'],traits:['texture','structure','detail'],pieces:['Caramel striped shirt','Brown corduroy flared trousers','Chocolate leather loafers']},
{name:'Poetry in motion',direction:'soft',top:'knit',bottom:'pleated',shoes:'flats',pattern:'plain',accessory:'necklace',colors:['#d3c7bc','#adbac0','#8d7e70','#bfa26b'],traits:['texture','relaxed','detail'],pieces:['Mushroom soft-knit sweater','Powder blue pleated skirt','Taupe Mary Jane flats']},
{name:'A study in contrast',direction:'minimal',top:'tank',bottom:'straight',shoes:'loafers',pattern:'plain',accessory:'necklace',colors:['#303934','#e8e0cc','#332b25','#c3a562'],traits:['neutral','fitted','structure'],pieces:['Black high-neck tank','Cream straight-leg trousers','Black minimal loafers']},
{name:'Meet me after work',direction:'tailored',top:'blazer',bottom:'shorts',shoes:'boots',pattern:'plain',accessory:'none',colors:['#676779','#797586','#393635','#9e957f'],traits:['structure','layers','detail'],pieces:['Slate oversized blazer','Slate tailored Bermuda shorts','Black mid-calf boots']},
{name:'Good company',direction:'expressive',top:'tee',bottom:'wide',shoes:'sneakers',pattern:'stripe',accessory:'bag',colors:['#3f6193','#b16045','#e9dfbe','#b5a164'],traits:['color','relaxed'],pieces:['Blue striped boxy tee','Rust wide-leg trousers','Cream retro sneakers']},
{name:'Wear it everywhere',direction:'utility',top:'jacket',bottom:'straight',shoes:'boots',pattern:'plain',accessory:'scarf',colors:['#a88154','#3e4943','#564031','#a44f3f'],traits:['texture','layers','structure'],pieces:['Tan canvas work jacket','Dark olive straight-leg pants','Brown lace-up boots']},
{name:'From another afternoon',direction:'vintage',top:'blouse',bottom:'skirt',shoes:'heels',pattern:'plain',accessory:'scarf',colors:['#dcbf84','#684b42','#735745','#8e614d'],traits:['detail','texture','fitted'],pieces:['Butter-yellow blouse','Chocolate A-line midi skirt','Brown low block heels']},
];
const backgrounds:Record<Direction,string>={soft:'#e6dfd1',minimal:'#dde0d1',tailored:'#dcded7',expressive:'#e5d8cc',utility:'#d8dccd',vintage:'#e2d7c6'};
export const LOOKS:Look[]=specs.map((s,i)=>({...s,id:`look-${i+1}`,background:backgrounds[s.direction],caption:s.pieces.slice(0,2).join(' + ')}));
